--CAMBIO DE NOMBRE DEL CAMPO INVENTARIO EN AJUSTES_DETALLE. AHORA EL NOMBRE ES ID_PRODUCTO_ALMACEN Y ESTE HARA REFERENCIA
--A L ATABLAPRODUCTO ALMACEN

--ALTER TABLE `ajustedetalle`
--CHANGE COLUMN `id_inventario` `id_producto_almacen` BIGINT(20) NULL DEFAULT NULL ;

-- ALTER OBSOLETO
